"""Build brief.pdf (≈4 pages) from the technical-brief content.

Run: python3 build_brief_pdf.py
Output: brief.pdf at project root.
"""

from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


ROOT = Path(__file__).resolve().parent
OUT = ROOT / "brief.pdf"


def build_styles():
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "title", parent=base["Title"], fontSize=18, leading=22,
            spaceAfter=3, textColor=colors.HexColor("#0B5A43"),
        ),
        "subtitle": ParagraphStyle(
            "subtitle", parent=base["Normal"], fontSize=9, leading=12,
            spaceAfter=1, textColor=colors.HexColor("#444"),
        ),
        "h1": ParagraphStyle(
            "h1", parent=base["Heading1"], fontSize=13, leading=16,
            spaceBefore=8, spaceAfter=4, textColor=colors.HexColor("#0B5A43"),
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"], fontSize=10.5, leading=14,
            spaceBefore=6, spaceAfter=3, textColor=colors.HexColor("#16A691"),
        ),
        "body": ParagraphStyle(
            "body", parent=base["BodyText"], fontSize=9, leading=12,
            spaceAfter=4, alignment=0,
        ),
        "bullet": ParagraphStyle(
            "bullet", parent=base["BodyText"], fontSize=9, leading=12,
            leftIndent=14, bulletIndent=2, spaceAfter=2,
        ),
        "mono": ParagraphStyle(
            "mono", parent=base["Code"], fontSize=7, leading=8.6,
            textColor=colors.HexColor("#0f1c17"),
        ),
        "caption": ParagraphStyle(
            "caption", parent=base["Italic"], fontSize=8, leading=10,
            textColor=colors.HexColor("#666"), spaceAfter=6,
        ),
    }
    return styles


def p(text, style):
    return Paragraph(text, style)


def bullet(text, style):
    return Paragraph(f"• {text}", style)


def build():
    doc = SimpleDocTemplate(
        str(OUT), pagesize=letter,
        rightMargin=0.6 * inch, leftMargin=0.6 * inch,
        topMargin=0.5 * inch, bottomMargin=0.5 * inch,
        title="EngageIQ Technical Brief", author="Ian Huang",
    )
    s = build_styles()
    story = []

    # ---------- Page 1: Header + Overview + Architecture diagram ----------
    story += [
        p("EngageIQ — Technical Brief", s["title"]),
        p("BAX-423 Big Data · Spring 2026 · Final Project · Option C", s["subtitle"]),
        p("Live application: <a href='https://engage-iq.streamlit.app/' color='#0B5A43'>https://engage-iq.streamlit.app/</a>", s["subtitle"]),
        p("Repository (code + dataset): <a href='https://github.com/iannh10/engageIQ' color='#0B5A43'>https://github.com/iannh10/engageIQ</a>", s["subtitle"]),
        p("Submission: Huang_Ian_BAX423_Final.zip &nbsp;·&nbsp; Author: Ian Huang", s["subtitle"]),
        Spacer(1, 8),

        p("1. System Overview", s["h1"]),
        p(
            "EngageIQ is a smart engagement opportunity scorer that ingests public records from GitHub, "
            "GH Archive, Forem (DEV.to) articles, and Hacker News, then ranks them for a professional "
            "deciding where to invest time online. The deployed Streamlit dashboard lets a user switch "
            "between the four test personas or build a custom profile, then surfaces ranked opportunities "
            "with &quot;Why this?&quot; explanations, LLM-generated engagement suggestions (Claude Haiku), "
            "inline engage / bookmark / skip feedback, and CSV/PDF brief downloads.",
            s["body"],
        ),
        p(
            "The offline grading dataset contains <b>76,972 unique records</b> across <b>all 15 required "
            "technical domains</b> and <b>4 sources</b>, materially exceeding the 10,000-record requirement. "
            "It is generated by <font name='Courier'>code/engageiq/data_generator.py</font> as a deterministic "
            "10,500-record baseline (700 records per domain), then expanded by live ingestion via "
            "<font name='Courier'>code/ingest_live.py</font> against the GitHub REST API, GH Archive, and "
            "Hacker News API, and the Forem (DEV.to) public articles API. The Forem collector needs no "
            "credentials, so the snapshot ships with Forem community records.",
            s["body"],
        ),

        p("2. Architecture and Data Pipeline", s["h1"]),
        Preformatted(
            "[Live public APIs]                          [Offline snapshot]\n"
            " GitHub REST v3   |                          data/engageiq_opportunities.csv\n"
            " GH Archive       |                          76,972 records · 15 domains · 4 sources\n"
            " Forem (DEV.to)   |\n"
            " Hacker News      |\n"
            "       |\n"
            "       v\n"
            " [ingest_live.py] -- normalize_record -->  [ Deduplication by stable id ]\n"
            "                                                       |\n"
            "                                                       v\n"
            "                          [ Sentence-BERT dense embeddings (all-MiniLM-L6-v2, cached .npy) ]\n"
            "                          [ TF-IDF cosine fallback if SBERT absent                         ]\n"
            "                                                       |\n"
            "                                                       v\n"
            "                          [ Multi-stage ranking                                            ]\n"
            "                          [  1. ANN candidate generation (top-500)                          ]\n"
            "                          [  2. Composite scoring: 45*rel + 15*health + 15*vis              ]\n"
            "                          [                       + 10*fresh + 10*effort + 5*fb             ]\n"
            "                          [  3. Diversity-aware re-rank (domain + source penalty)           ]\n"
            "                                                       |\n"
            "                                                       v\n"
            "                          [ Adaptive learning                                              ]\n"
            "                          [ engage / bookmark / skip -> tag weights                         ]\n"
            "                          [ durable feedback_events.json replay at startup                  ]\n"
            "                                                       |\n"
            "                                                       v\n"
            "                          [ Streamlit dashboard: landing, ranked cards with 'Why this?',    ]\n"
            "                          [ per-card feedback, trend analytics, CSV / PDF brief export      ]\n",
            s["mono"],
        ),
        Spacer(1, 6),
        p(
            "<b>Deduplication.</b> Every record carries a <font name='Courier'>stable_id</font> derived "
            "from <font name='Courier'>sha1(source | title | url)</font>. Offline generation collects "
            "records into a dictionary keyed by id; live append goes through "
            "<font name='Courier'>pandas.drop_duplicates(subset=[&quot;id&quot;])</font>. Both paths "
            "converge on identity-based dedup before scoring.",
            s["body"],
        ),
        p(
            "<b>Streaming caveat.</b> Live ingestion is invoked as a batch script rather than a "
            "continuously running stream. The <font name='Courier'>normalize_record</font> schema and "
            "dedup mechanism extend cleanly to a polling or webhook driver — flagged in §6.",
            s["body"],
        ),
        PageBreak(),
    ]

    # ---------- Page 2: BAX-423 Techniques + Benchmarks ----------
    story += [
        p("3. BAX-423 Techniques", s["h1"]),
        p("EngageIQ integrates three techniques from the course and benchmarks the matching/ranking layer.", s["body"]),

        p("Technique 1 — Semantic embedding retrieval (Sentence-BERT)", s["h2"]),
        p(
            "Each opportunity is represented by the concatenation of <i>title + body + domain + tags</i>. "
            "Each user profile is represented by <i>name + interests + goal + skillsets + avoid</i>. Both "
            "are encoded with <font name='Courier'>sentence-transformers/all-MiniLM-L6-v2</font> and "
            "normalized to unit length. The opportunity matrix is cached in "
            "<font name='Courier'>data/engageiq_sbert_embeddings.npy</font> (~118 MB) with metadata in the "
            "sibling .json, so the dashboard reuses the embeddings after the first build instead of "
            "recomputing 77k vectors per startup. Cosine similarity (a single matrix-vector multiply on "
            "normalized vectors) returns the top-K candidate set before scoring. If "
            "<font name='Courier'>sentence-transformers</font> is unavailable in a grading environment, "
            "the ranker falls back to TF-IDF cosine retrieval so the application remains runnable.",
            s["body"],
        ),

        p("Technique 2 — Multi-stage recommendation and ranking", s["h2"]),
        p(
            "Candidate generation retrieves the top-500 semantically related records. A scoring layer "
            "then computes a composite engagement score:",
            s["body"],
        ),
        Preformatted(
            "final_score = 45*relevance + 15*health + 15*visibility\n"
            "            + 10*freshness + 10*effort_fit + 20*feedback_affinity",
            s["mono"],
        ),
        Spacer(1, 4),
        p(
            "Health combines activity, comments, and contributors minus toxicity. Visibility combines "
            "platform score, stars, and growth rate. Effort fit penalizes opportunities far from the "
            "persona's weekly time budget. Persona-specific boosts add trend-velocity weight for the "
            "journalist profile, good-first-issue weight for beginner-oriented profiles, infra-domain "
            "weight for DevOps, and developer-tools weight for the startup founder. A final "
            "diversification pass penalizes repeated domains and over-represented sources so the top-10 "
            "does not collapse into a narrow slice of the dataset.",
            s["body"],
        ),

        p("Technique 3 — Adaptive learning from feedback", s["h2"]),
        p(
            "Engage / bookmark / skip events translate into tag-level weight deltas (+0.30, +0.20, "
            "−0.30) that feed back into <font name='Courier'>feedback_affinity</font> on the next render. "
            "Real dashboard clicks are persisted to <font name='Courier'>data/feedback_events.json</font> "
            "and replayed into the ranker at startup via "
            "<font name='Courier'>FeedbackStore.apply_to_ranker</font>, so learned preferences survive "
            "restarts. The simulation in <font name='Courier'>code/engageiq/learning.py</font> runs 60 "
            "rounds of engage/skip choices per persona and reports Precision@10 before and after "
            "adaptation.",
            s["body"],
        ),

        p("4. Benchmarks", s["h1"]),
        p(
            "<b>Retrieval backend benchmark (<font name='Courier'>code/evaluate_personas.py</font>).</b> "
            "The same scoring pipeline is run with the SBERT dense backend and with the TF-IDF fallback. "
            "Precision@10 is computed from persona-interest token overlap on the top-10 titles, bodies, "
            "and tags.",
            s["body"],
        ),
    ]

    bench_data = [
        ["Persona", "TF-IDF P@10", "SBERT P@10 (before)", "SBERT P@10 (after 60 rounds)", "Δ"],
        ["Sofia ML Student", "1.00", "1.00", "1.00", "+0.00"],
        ["David DevOps Engineer", "0.90", "0.90", "1.00", "+0.10"],
        ["Lina Data Journalist", "1.00", "1.00", "1.00", "+0.00"],
        ["Raj Startup Founder", "1.00", "1.00", "1.00", "+0.00"],
    ]
    bench_table = Table(bench_data, colWidths=[1.7 * inch, 0.9 * inch, 1.3 * inch, 1.9 * inch, 0.5 * inch])
    bench_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B5A43")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cfd6d3")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f7f5")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story += [bench_table, Spacer(1, 6)]
    story += [
        p(
            "SBERT and TF-IDF achieve similar Precision@10 on this offline metric because three of "
            "four personas already saturate it. SBERT nevertheless produces materially better candidate "
            "ordering for off-vocabulary queries in the dashboard (e.g., a custom profile mentioning "
            "&quot;observability tooling&quot; retrieves Kubernetes/SRE records even when the literal "
            "token is absent). Adaptive learning lifts David from 0.90 → 1.00, the only persona below "
            "ceiling at start. The ceiling effect is a known weakness of the simulated relevance signal "
            "and is addressed in §6.",
            s["body"],
        ),
        PageBreak(),
    ]

    # ---------- Page 3: Persona × Capability Pass/Fail + Per-Persona ----------
    story += [
        p("5. Persona Test Results", s["h1"]),
        p("5.1 Persona × Capability Pass/Fail Matrix", s["h2"]),
    ]

    cap_data = [
        ["Persona", "1. Multi-source\ningestion + dedup", "2. SBERT\nretrieval", "3. Multi-stage\nranking", "4. Adaptive\nlearning", "5. Batch\nanalytics", "6. Dashboard\n+ brief"],
        ["Sofia ML Student\n(Portfolio Builder)",       "PASS", "PASS", "PASS", "PASS", "PASS", "PASS"],
        ["David DevOps Engineer\n(Niche Community)",    "PASS", "PASS", "PASS", "PASS", "PASS", "PASS"],
        ["Lina Data Journalist\n(Trend Spotter)",       "PASS", "PASS", "PASS", "PASS", "PASS", "PASS"],
        ["Raj Startup Founder\n(Marketing-Focused)",    "PASS", "PASS", "PASS", "PASS", "PASS", "PASS"],
    ]
    cap_table = Table(
        cap_data,
        colWidths=[1.8 * inch, 0.95 * inch, 0.85 * inch, 0.95 * inch, 0.85 * inch, 0.75 * inch, 0.85 * inch],
    )
    cap_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B5A43")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cfd6d3")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f7f5")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TEXTCOLOR", (1, 1), (-1, -1), colors.HexColor("#0B5A43")),
            ("FONTNAME", (1, 1), (-1, -1), "Helvetica-Bold"),
        ])
    )
    story += [cap_table, Spacer(1, 10)]

    story += [
        p("5.2 Per-persona observations", s["h2"]),
        p(
            "<b>Sofia ML Student (Portfolio Builder).</b> Top-10 is dominated by Machine Learning and "
            "Beginner Coding domains with ≥3 good-first-issue GitHub records, no C++/Rust items (the "
            "<font name='Courier'>avoid</font> filter strips them), and per-item effort estimates under "
            "one hour. The engagement brief CSV/PDF gives her a one-page weekly action list.",
            s["body"],
        ),
        p(
            "<b>David DevOps Engineer (Niche Community).</b> Top-10 emphasizes DevOps/K8s and Cloud APIs, "
            "with infrastructure community labels and discussion-oriented surfaces (DEV.to devops/kubernetes "
            "tags, GitHub issues). The DevOps boost adds +8 to DevOps/Cloud-API domains and the "
            "3 hr/week time budget pulls in low-effort items. Adaptive learning lifts P@10 from 0.90 → "
            "1.00 over 60 rounds.",
            s["body"],
        ),
        p(
            "<b>Lina Data Journalist (Trend Spotter).</b> Persona-conditional boost adds "
            "10·growth_rate + 5·freshness to the composite score, surfacing fast-rising opportunities "
            "first. The analytics tab independently shows the avg-growth-by-domain bar chart, fastest "
            "communities, and daily volume — directly supporting her week-over-week trend brief.",
            s["body"],
        ),
        p(
            "<b>Raj Startup Founder (Marketing-Focused).</b> Boost prioritizes Developer Tools, Cloud "
            "APIs, and Trending Open-Source domains while penalizing GameDev/Embedded/Mobile. Skip "
            "feedback further deprioritizes low-fit records via tag-weight decay. Result is a stream of "
            "CLI/SDK/API discussion threads suitable for product-aware engagement.",
            s["body"],
        ),
        PageBreak(),
    ]

    # ---------- Page 4: Limitations + Future Work + Prompts ----------
    story += [
        p("6. Limitations and Future Work", s["h1"]),
        p("Limitations", s["h2"]),
        bullet("The offline snapshot is schema-compatible with live API records but is partly synthetic. Live ingestion was tested end-to-end against GitHub, GH Archive, Hacker News, and the Forem (DEV.to) public articles API; the Forem path needs no credentials and runs unauthenticated against dev.to/api/articles.", s["bullet"]),
        bullet("The project specification lists Reddit/PRAW as one of the four data sources. Reddit was replaced with Forem (DEV.to) because Reddit Data API approval is a multi-week process that could not be completed within the project timeline. Forem provides equivalent public developer-community discussions across all 15 domains and satisfies the same rubric intent.", s["bullet"]),
        bullet("The pipeline is batch-driven by <font name='Courier'>ingest_live.py</font> rather than a continuously running stream.", s["bullet"]),
        bullet("The offline Precision@10 metric ceilings at 1.00 for three of four personas because simulated relevance is derived from persona-interest token overlap on the same text used for retrieval. A held-out hand-labeled relevance set or NDCG@10 would be a stronger metric and is the highest-value next step.", s["bullet"]),
        bullet("LLM-generated suggestions require <font name='Courier'>ANTHROPIC_API_KEY</font> to be set; the app falls back to rule-based templates when the key is absent (e.g., on the public Streamlit Cloud deployment without secrets configured).", s["bullet"]),
        bullet("Streamlit Cloud's filesystem is ephemeral; <font name='Courier'>feedback_events.json</font> writes survive within a session but reset on container restart. The persistence path is correct for local runs and migrates cleanly to a managed database.", s["bullet"]),
        bullet("Live ingestion has a domain-inference bias: the <font name='Courier'>infer_domain</font> helper in <font name='Courier'>collectors.py</font> over-attributes GH Archive events to Embedded Systems and Developer Tools because of a permissive keyword list. The synthetic baseline (10,500 records, 700 per domain) is unaffected.", s["bullet"]),

        p("Future improvements", s["h2"]),
        bullet("Replace the batch ingestion script with scheduled GH Archive polling and webhook listeners.", s["bullet"]),
        bullet("Add a held-out relevance set and replace Precision@10 with NDCG@10 to remove the ceiling effect.", s["bullet"]),
        bullet("<b>Implemented:</b> per-card suggested actions are now generated by Claude Haiku using the opportunity title, platform, domain, and persona profile, cached per (opportunity, persona) pair.", s["bullet"]),
        bullet("Migrate adaptive learning from tag-weight deltas to a contextual bandit so exploration vs exploitation becomes explicit.", s["bullet"]),
        bullet("Add authenticated user accounts so multi-user feedback can be separated and survive deploys.", s["bullet"]),

        p("7. AI Tools and Prompts", s["h1"]),
        p(
            "EngageIQ was built with Claude Code as the primary AI pair and Codex by OpenAI as a "
            "secondary assistant, in line with the project's &quot;AI tools encouraged&quot; rule. "
            "The full prompt log is in <font name='Courier'>prompts.md</font>. Highlights:",
            s["body"],
        ),
        bullet("<i>Inspect the docx and one-pager; identify required capabilities, rubric criteria, data sources, test personas, and whether the app needs to track personal platform activity.</i> Used to extract the rubric and define scope.", s["bullet"]),
        bullet("<i>Build a runnable EngageIQ application matching Option C: multi-source ingestion schema, offline 10,000+ record dataset, embedding-style retrieval, engagement ranking, feedback learning, trend analytics, dashboard, and CSV/PDF brief export.</i> Produced the initial scaffolding and module split.", s["bullet"]),
        bullet("<i>Upgrade the retrieval pipeline from TF-IDF fallback to Sentence-BERT dense embeddings with a cached local embedding matrix and benchmark the four provided personas.</i> Drove the SBERT integration and the cache + signature logic.", s["bullet"]),
        bullet("<i>Add durable feedback logging so engage/bookmark/skip events are saved to <font name='Courier'>data/feedback_events.json</font>, replayed into ranking weights on startup, and documented as part of adaptive learning.</i> Produced <font name='Courier'>feedback_store.py</font> and the startup replay path.", s["bullet"]),
        bullet("<i>Refine the UI into a more complete EngageIQ platform experience with a landing page, light/dark mode, custom profile scoring, saved profiles, logo integration, and a cleaner one-button landing call to action.</i> Produced the Streamlit landing page, theme toggle, custom profile fields, and per-card feedback buttons.", s["bullet"]),
        bullet("<i>Score the project against the rubric, surface discrepancies between the deployed Streamlit app and the local custom-HTML build, and update the brief and persona pass/fail table for submission.</i> Drove the final brief, the persona × capability matrix, and the Streamlit UI fixes that produced the deployed app.", s["bullet"]),
    ]

    doc.build(story)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    build()
